# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbA-nWlvma-O7YabJUfMBRlGsfyJdfXO

# bootcamp 2.0 assingment 1

##1.Find out all the types of error that we have encountered in our lecture and why? Also include the examples.

###Ans:
NameError: name 'Print' is not defined

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Good Evening")?

SyntaxError: EOL while scanning string literal

SyntaxError: invalid syntax

SyntaxError: can't assign to operator

 10ten = 10
        ^
SyntaxError: invalid syntax

TypeError: can only concatenate str (not "int") to str

TypeError: can only concatenate str (not "int") to str

TypeError: unsupported operand type(s) for +: 'int' and 'str'

TypeError                                 Traceback (most recent call last)
<ipython-input-77-6f0a8cb6799f> in <module>
      5 year_of_birth = input("year_of_birth: ")
      6 
----> 7 age = 2022 - year_of_birth
      8 
      9 print(f'''

TypeError: unsupported operand type(s) for -: 'int' and 'str'

int A
        ^
SyntaxError: invalid syntax

ValueError: invalid literal for int() with base 10: '10.2'

ValueError: invalid literal for int() with base 10: '

##2.Take input A and B and print their sum, mul, div, square of the nos.
"""

A = 5
B = 4
print(A)
print(B)
print(A+B)
print(A*B)
print(A/B)

"""##3.How many reserve keywords are there in python and why we should not use them as a variable name.
 Ans : There are  33 reversed keywords are present in python
 we should not use them as a variable beacuse In Python, keywords are case sensitive. This number can vary slightly over the course of time.

# 4.Create email ids with the user inputs. in the following format - lastname.firstname@gmail.com
"""

firstName,  lastname = "Abhijeet",  "shandilya"

print(f"{lastname}.{firstName}@gmail.com")

"""# 5 Try to print the following lines -
Hi I'm Sunny

My address is 22\3

I earn 20$ daily.
"""

print(f"""
hi i`m sunny
my address is 22\3
i earn 20$ daily
""")

"""#6.Take user input (name, address, date of birth etc) to fill a form for your college and print their email IDs

"""

Name = input("Name: ") 
address = input("address: ")
date_of_birth = input("date_of_birth: ")
branch = input("branch: ")

"""#7 Convert the following -
"22.4" into integer

"22" into complex no.

"""

